version: "3.8"

services:
  mongodb:
    image: mongo:lts
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
       - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
       - ./E-GO-db:/E-GO-db
  server:
    depends_on:
      - mongodb
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $SERVER_LOCAL_PORT:$SERVER_DOCKER_PORT
      - $SOCKET_LOCAL_PORT:$SOCKET_DOCKER_PORT
    environment:
      - DB_HOST=$MONGODB_HOST
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
  frontend:
    depends_on:
      - server
    build: ./frontend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $FRONTEND_LOCAL_PORT:$FRONTEND_DOCKER_PORT
    stdin_open: true
    tty: true